return {}
-- return {
--   "catppuccin/nvim",
--   name = "catppuccin",
--   priority = 1000,
--   config = function ()
--     -- Setup plugins
--     require("catppuccin").setup()
--     vim.cmd.colorscheme "catppuccin"
--   end
-- }
